name: Freeze
version: 1.2
main: cy.freeze
author: Cyttt

commands:
  freeze:
    aliases:
      - cyfreeze
      - cyf
  unfreeze:
    aliases:
      - cyfreeze
      - cyf

permissions:
  freeze.use:
    description: Node for /freeze or /unfreeze
